### ISSUE TITLE
Crashing with error "failed to process contract actions"

### ISSUE THREAD

**Issue by multikatt** [SiaFoundation/hostd#144]
### Current Behavior

I've had 9 crashes the last few days with the following message:
```
Aug 09 14:53:00 ds49357 hostd[624060]: panic: failed to process contract actions
Aug 09 14:53:00 ds49357 hostd[624060]: goroutine 59 [running]:
Aug 09 14:53:00 ds49357 hostd[624060]: go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x0?, {0x0?, 0x0?, 0xc002d34080?})
Aug 09 14:53:00 ds49357 hostd[624060]:         go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
Aug 09 14:53:00 ds49357 hostd[624060]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000020410, {0xc00260e000, 0x2, 0x2})
Aug 09 14:53:00 ds49357 hostd[624060]:         go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
Aug 09 14:53:00 ds49357 hostd[624060]: go.uber.org/zap.(*Logger).Panic(0xc0003a6500?, {0xf299f0?, 0x0?}, {0xc00260e000, 0x2, 0x2})
Aug 09 14:53:00 ds49357 hostd[624060]:         go.uber.org/zap@v1.24.0/logger.go:258 +0x59
Aug 09 14:53:00 ds49357 hostd[624060]: go.sia.tech/hostd/host/contracts.(*ContractManager).processActions(0xc0003a6500)
Aug 09 14:53:00 ds49357 hostd[624060]:         go.sia.tech/hostd/host/contracts/actions.go:75 +0x2c5
Aug 09 14:53:00 ds49357 hostd[624060]: created by go.sia.tech/hostd/host/contracts.NewManager
Aug 09 14:53:00 ds49357 hostd[624060]:         go.sia.tech/hostd/host/contracts/manager.go:532 +0x43a
```

I haven't been working doing anything while this has happened. Cpu/ram has been looking good. I have a few contracts expiring now, so might be related to that.

### Expected Behavior

No crash.

### Version

Built from 7d5d625fff26e60d242401401025e75645b05652

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Linux

### Anything else?

DM me on discord (@trevligt) if you need any logs etc.

**Comment by n8maninger** [comment]
Fixed by #146
